### ISSUE TITLE
Practica 8 Veridica

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-de-melissa#3]
[Practica 8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-de-melissa/files/10026756/Practica.8.pdf)

**Comment by Valentiin01** [comment]
Calificación 30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
